sudo: false
language: node_js
node_js:
- 10
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_e6eb22065824_key -iv $encrypted_e6eb22065824_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- docker build -t mufdvr/git_forks .
deploy:
  provider: script
  script: bash docker_deploy.sh
  on:
    branch: master
branches:
  only:
  - master
